name: Cypress Tests on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Cypress Tests on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
